#!/usr/bin/env python3

import traceback
import sys
from utils.checker_helpers import wrap_student_module
from utils.import_reporter import BadImport

# This file is executed when participant clicks "Execute code".
# You only need to modify constants below.

ALLOWED_LIBS = ['typing', 'math']


def main() -> None:
    try:
        wrap_student_module('participant.py', ALLOWED_LIBS, False)

    except BadImport as exc:
        if exc.args[0] == 'unicodedata':
            msg = "Používáte v názvech funkcí nebo proměnných ne-ASCII znaky."
        else:
            msg = "Spuštěný kód používá nepovolenou knihovnu: " + exc.args[0]
        print(msg)  # for exec log

    except Exception:
        for line in traceback.format_exception(*sys.exc_info()):
            if (line.strip().startswith('File "participant.py"')
                    or not line.strip().startswith('File')):
                print(line, end='')


if __name__ == '__main__':
    main()
