#!/usr/bin/env python3

import os
import shutil
import sys
from distutils.dir_util import copy_tree

# Prepare code for execution.

# Participant`s code is in file path sys.argv[1].
# Output code should be created in file path sys.argv[2].
# Global module directory is in directory os.path.dirname(sys.argv[0]).
# Sandbox directory is in "./box/"

exec_filename = 'exec' if len(sys.argv) >= 6 and sys.argv[5] == "exec" else "check"
shutil.copy2(os.path.join(os.path.dirname(sys.argv[0]), exec_filename), sys.argv[2])
shutil.copy2(sys.argv[1], os.path.join("box", "participant.py"))
copy_tree(os.path.join(sys.argv[3], "prog_check_utils"), os.path.join("box", "utils"))

files_to_copy = []
for x in files_to_copy:
    shutil.copy2(os.path.join(os.path.dirname(sys.argv[0]), x), os.path.join("box", x))
